# Generated by Django 4.2.7 on 2025-10-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_score', models.IntegerField(blank=True, null=True)),
                ('cv_resume', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
