# Generated by Django 4.2.7 on 2025-10-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidature',
        ),
        migrations.AlterUniqueTogether(
            name='sociallink',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='sociallink',
            table='candidatures',
        ),
    ]
