# Generated by Django 4.2.7 on 2025-10-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_candidature_alter_sociallink_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sociallink',
            unique_together={('user', 'platform')},
        ),
        migrations.AlterModelTable(
            name='sociallink',
            table='user_social_links',
        ),
    ]
