# Generated by Django 5.2.7 on 2025-10-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_sociallink_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resume_text',
        ),
        migrations.AddField(
            model_name='user',
            name='cv_resume',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
