# Generated by Django 4.2.7 on 2025-09-27 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='category',
        ),
        migrations.AddField(
            model_name='formation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='enrolled_formations', to=settings.AUTH_USER_MODEL),
        ),
    ]
