# Generated by Django 4.2.7 on 2025-09-27 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_formation_category_formation_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='courses.category'),
        ),
    ]
