# Generated by Django 4.2.7 on 2025-09-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseapplication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterUniqueTogether(
            name='courseapplication',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='cv',
            field=models.FileField(blank=True, help_text="Candidate's CV file", null=True, upload_to='applications/cv/'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='application_message',
            field=models.TextField(blank=True, help_text='Motivation letter from candidate to instructor', null=True),
        ),
    ]
