# Generated by Django 4.2.7 on 2025-09-28 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_courseapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='quiz_score',
            field=models.PositiveIntegerField(blank=True, help_text='Quiz score percentage (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='quiz_attempt',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to full quiz attempt details', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_applications', to='courses.quizattempt'),
        ),
    ]
