# Generated by Django 4.2.7 on 2025-09-28 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_courseapplication_quiz_score_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=set(),
        ),
    ]
