# Generated by Django 4.2.7 on 2025-10-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_quizattempt_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='cv_resume',
            field=models.TextField(blank=True, help_text='AI-generated resume of the CV', null=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='cv_score',
            field=models.PositiveIntegerField(blank=True, help_text='AI evaluation score of the CV', null=True),
        ),
    ]
