# Generated by Django 5.2.7 on 2025-10-20 16:55

from django.db import migrations, models  # ✅ AJOUTEZ ", models" ici


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courseapplication_cv_resume_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='courseapplication',
            index=models.Index(fields=['formation', 'status'], name='app_form_status_idx'),
        ),
        migrations.AddIndex(
            model_name='courseapplication',
            index=models.Index(fields=['candidate'], name='app_candidate_idx'),
        ),
        migrations.AddIndex(
            model_name='courseapplication',
            index=models.Index(fields=['-created_at'], name='app_created_idx'),
        ),
    ]