# Generated by Django 4.2.7 on 2025-10-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_add_indexes_for_performance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='courseapplication',
            name='app_form_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='courseapplication',
            name='app_candidate_idx',
        ),
        migrations.RemoveIndex(
            model_name='courseapplication',
            name='app_created_idx',
        ),
        migrations.AddField(
            model_name='formation',
            name='learning_points',
            field=models.JSONField(blank=True, default=list, help_text='List of learning points'),
        ),
        migrations.AddField(
            model_name='formation',
            name='requirements',
            field=models.JSONField(blank=True, default=list, help_text='List of prerequisites'),
        ),
    ]
