# Generated by Django 4.2.7 on 2025-10-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_courseapplication_app_form_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='cv_analysis',
            field=models.JSONField(blank=True, help_text='Detailed AI analysis of CV', null=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='cv_text',
            field=models.TextField(blank=True, help_text='Extracted text from CV', null=True),
        ),
    ]
