# Generated by Django 4.2.7 on 2025-10-23 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_courseapplication_cv_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='cv_score',
            field=models.PositiveIntegerField(blank=True, help_text='AI-generated CV score (0-100)', null=True),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=60, help_text='Duration in minutes')),
                ('meeting_type', models.CharField(choices=[('online', 'Online (Teams/Zoom)'), ('in_person', 'In Person'), ('phone', 'Phone Call')], default='online', max_length=20)),
                ('meeting_link', models.URLField(blank=True, help_text='Meeting link for online interviews', null=True)),
                ('location', models.CharField(blank=True, help_text='Location for in-person interviews', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the interview', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='courses.courseapplication')),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['application', '-scheduled_date'], name='courses_int_applica_8adfb4_idx'), models.Index(fields=['scheduled_date'], name='courses_int_schedul_615a3e_idx')],
            },
        ),
    ]
