# Generated by Django 4.2.7 on 2025-10-23 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_courseapplication_cv_score_interview'),
        ('notifications', '0002_remove_notification_data_notification_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='courses.interview'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('application_withdrawn', 'Application Withdrawn'), ('interview_scheduled', 'Interview Scheduled'), ('interview_cancelled', 'Interview Cancelled'), ('interview_rescheduled', 'Interview Rescheduled')], max_length=50),
        ),
    ]
